name: Vitre
options:
  bundleIdPrefix: xyz.gurubhat
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"

targets:
  Vitre:
    type: application
    platform: macOS
    sources:
      - path: Vitre
        type: group
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: xyz.gurubhat.vitre
        SWIFT_VERSION: "5.0"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        DEVELOPMENT_TEAM: "3BHALMRSXD"
        GENERATE_INFOPLIST_FILE: "YES"
        INFOPLIST_KEY_LSUIElement: "YES"
    info:
      path: Vitre/Info.plist
      properties:
        LSUIElement: true